#!/usr/bin/env bash
# scripts/setup-dev.sh — bootstrap the local development environment.
#
# Every tool used here lives in `shell.nix`; the script enters a Nix
# subshell so PATH resolves to the pinned versions regardless of
# whether the caller has already run `nix-shell`. The Nix shell is
# the single source of truth for tool versions — no fallback
# installer paths. Safe to re-run; each install step is idempotent.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v nix-shell >/dev/null 2>&1; then
    echo "{{project-name}}: setup-dev — nix-shell not on PATH" >&2
    echo "  hint: install Nix from https://nixos.org/download" >&2
    exit 1
fi

# Regenerate `rust-toolchain.toml` from `.tool-versions`. The toolchain
# file is a derived artifact — `.tool-versions` is the canonical
# source of the pinned Rust channel. Generating here means a single
# `.tool-versions` edit propagates atomically; check-tool-versions
# still enforces equality so any out-of-band edit is flagged.
rust_version=$(grep -E '^rust\s' .tool-versions | awk '{print $2}')
cat > rust-toolchain.toml <<EOF
# Auto-generated by scripts/setup-dev.sh from .tool-versions.
# Edit .tool-versions instead and re-run \`just setup\`.
[toolchain]
channel = "${rust_version}"
profile = "minimal"
components = ["clippy", "rustfmt"]
EOF

nix-shell --run '
    set -euo pipefail

    # `rustup show active-toolchain` reads rust-toolchain.toml and
    # triggers a download if the pinned channel is not installed yet.
    echo "{{project-name}}: setup-dev — ensuring Rust toolchain matches rust-toolchain.toml…"
    rustup show active-toolchain >/dev/null

    # Authoritative match against `.tool-versions`; aborts on drift
    # so a misaligned nix-shell surfaces here instead of in CI.
    echo "{{project-name}}: setup-dev — verifying pinned tools…"
    just check-tool-versions

    echo "{{project-name}}: setup-dev — installing Node devDependencies for commitlint…"
    npm ci --no-audit --no-fund

    echo "{{project-name}}: setup-dev — installing git hooks via pre-commit…"
    pre-commit install --install-hooks \
        --hook-type pre-commit \
        --hook-type pre-push \
        --hook-type commit-msg

    echo "{{project-name}}: setup-dev — done."
'
